configuration:
  automap:
    - accounts
    - accounts_bugs
    - accounts_cases
    - accounts_contacts
    - accounts_opportunities
    - address_book
    - aop_case_events
    - aop_case_updates
    - aor_charts
    - aor_conditions
    - aor_fields
    - aor_reports
    - calls
    - calls_contacts
    - calls_reschedule
    - calls_users
    - campaigns
    - campaign_log
    - campaign_trkrs
    - cases
    - cases_bugs
    - contacts
    - contacts_bugs
    - contacts_cases
    - contacts_users
    - emails
    - emails_beans
    - emails_email_addr_rel
    - emails_text
    - email_addresses
    - email_addr_bean_rel
    - email_cache
    - email_marketing
    - email_marketing_prospect_lists
    - email_templates
    - meetings
    - meetings_contacts
    - meetings_users
    - prospect_lists
    - prospect_lists_prospects
    - prospect_list_campaigns
    - tasks
    - project
    - projects_accounts
    - projects_bugs
    - projects_cases
    - projects_contacts
    - projects_opportunities
    - projects_products
    - project_task
    - opportunities
    - opportunities_contacts


# ----------------------DISABLED----------------
#    - leads
#    - calls_leads
#    - meetings_leads
#    - folders
#    - folders_rel
#    - folders_subscriptions
#    - import_maps
#    - inbound_email
#    - inbound_email_autoreply
#    - inbound_email_cache_ts
#    - job_queue
#    - linked_documents
#    - notes
#    - oauth_consumer
#    - oauth_nonce
#    - oauth_tokens
#    - opportunities
#    - opportunities_contacts
#    - opportunities_cstm
#    - outbound_email
#    - project
#    - projects_accounts
#    - projects_bugs
#    - projects_cases
#    - projects_contacts
#    - projects_opportunities
#    - projects_products
#    - project_cstm
#    - project_task
#    - qcrm_homepage
#    - qcrm_savedsearch
#    - qcrm_users
#    - prospects
#    - relationships
#    - releases
#    - roles
#    - roles_modules
#    - roles_users
#    - saved_search
#    - schedulers
#    - securitygroups
#    - securitygroups_acl_roles
#    - securitygroups_default
#    - securitygroups_records
#    - securitygroups_users
#    - sugarfeed
#    - tracker
#    - upgrade_history
#    - users
#    - users_cstm
#    - users_feeds
#    - users_last_import
#    - users_password_link
#    - users_signatures
#    - user_preferences
#    - vcals
#    - versions