<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/

$dictionary['mkt_Inspection_Washing'] = array(
    'table'              => 'mkt_inspection_washing',
    'audited'            => true,
    'inline_edit'        => true,
    'duplicate_merge'    => true,
    'fields'             => array(
        'execution_date'           =>
            array(
                'required'                  => true,
                'name'                      => 'execution_date',
                'vname'                     => 'LBL_EXECUTION_DATE',
                'type'                      => 'datetimecombo',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'size'                      => '20',
                'enable_range_search'       => false,
                'dbType'                    => 'datetime',
                'display_default'           => 'now&10:00am',
            ),
        'type'                     =>
            array(
                'required'                  => true,
                'name'                      => 'type',
                'vname'                     => 'LBL_TYPE',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_type_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'water_hardness'           =>
            array(
                'required'                  => true,
                'name'                      => 'water_hardness',
                'vname'                     => 'LBL_WATER_HARDNESS',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => '17',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_water_hardness_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'ph_pool_tornasole'        =>
            array(
                'required'                  => true,
                'name'                      => 'ph_pool_tornasole',
                'vname'                     => 'LBL_PH_POOL_TORNASOLE',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => '7',
                'no_default'                => false,
                'comments'                  => 'Ph in vasca: diluizione detergente - Metodo cartina tornasole',
                'help'                      => 'Ph in vasca: diluizione detergente - Metodo cartina tornasole',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_ph_pool_tornasole_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'ph_pool_titolazione'      =>
            array(
                'required'                  => true,
                'name'                      => 'ph_pool_titolazione',
                'vname'                     => 'LBL_PH_POOL_TITOLAZIONE',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => 'neutral',
                'no_default'                => false,
                'comments'                  => 'Ph in vasca: diluizione detergente - Metodo Titolazione',
                'help'                      => 'Ph in vasca: diluizione detergente - Metodo Titolazione',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_smile_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'pump_rev_detergent'       =>
            array(
                'required'                  => true,
                'name'                      => 'pump_rev_detergent',
                'vname'                     => 'LBL_PUMP_REV_DETERGENT',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_pump_rev_1_7',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'pump_rev_brill'           =>
            array(
                'required'                  => true,
                'name'                      => 'pump_rev_brill',
                'vname'                     => 'LBL_PUMP_REV_BRILL',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_pump_rev_1_7',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'glass_dry_time'           =>
            array(
                'required'                  => true,
                'name'                      => 'glass_dry_time',
                'vname'                     => 'LBL_GLASS_DRY_TIME',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => 'never',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_glass_dry_time_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'plate_dry_time'           =>
            array(
                'required'                  => true,
                'name'                      => 'plate_dry_time',
                'vname'                     => 'LBL_PLATE_DRY_TIME',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => 'never',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_glass_dry_time_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'detergent_leftover'       =>
            array(
                'required'                  => true,
                'name'                      => 'detergent_leftover',
                'vname'                     => 'LBL_DETERGENT_LEFTOVER',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => 'neutral',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_smile_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'starch_presence'          =>
            array(
                'required'                  => true,
                'name'                      => 'starch_presence',
                'vname'                     => 'LBL_STARCH_PRESENCE',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => 'neutral',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_smile_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'limestone_presence'       =>
            array(
                'required'                  => true,
                'name'                      => 'limestone_presence',
                'vname'                     => 'LBL_LIMESTONE_PRESENCE',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => 'neutral',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_smile_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'grease_presence'          =>
            array(
                'required'                  => true,
                'name'                      => 'grease_presence',
                'vname'                     => 'LBL_GREASE_PRESENCE',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'default'                   => 'neutral',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'inspection_smile_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'machine_brand'            =>
            array(
                'required'                  => true,
                'name'                      => 'machine_brand',
                'vname'                     => 'LBL_MACHINE_BRAND',
                'type'                      => 'varchar',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
            ),
        'machine_model'            =>
            array(
                'required'                  => true,
                'name'                      => 'machine_model',
                'vname'                     => 'LBL_MACHINE_MODEL',
                'type'                      => 'varchar',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
            ),
        'softener_presence'        =>
            array(
                'required'                  => true,
                'name'                      => 'softener_presence',
                'vname'                     => 'LBL_SOFTENER_PRESENCE',
                'type'                      => 'enum',
                'massupdate'                => '1',
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => 100,
                'size'                      => '20',
                'options'                   => 'yes_no_list',
                'studio'                    => 'visible',
                'dependency'                => false,
            ),
        'load_liters'              =>
            array(
                'required'                  => true,
                'name'                      => 'load_liters',
                'vname'                     => 'LBL_LOAD_LITERS',
                'type'                      => 'int',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
                'enable_range_search'       => false,
                'disable_num_format'        => '1',
                'min'                       => 0,
                'max'                       => 999,
                'validation'                =>
                    array(
                        'type' => 'range',
                        'min'  => 0,
                        'max'  => 999,
                    ),
            ),
        'wash_cycle_liters'        =>
            array(
                'required'                  => true,
                'name'                      => 'wash_cycle_liters',
                'vname'                     => 'LBL_WASH_CYCLE_LITERS',
                'type'                      => 'int',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
                'enable_range_search'       => false,
                'disable_num_format'        => '1',
                'min'                       => 0,
                'max'                       => 999,
                'validation'                =>
                    array(
                        'type' => 'range',
                        'min'  => 0,
                        'max'  => 999,
                    ),
            ),
        'number_daily_covers'      =>
            array(
                'required'                  => false,
                'name'                      => 'number_daily_covers',
                'vname'                     => 'LBL_NUMBER_DAILY_COVERS',
                'type'                      => 'varchar',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
            ),
        'cover_composition'        =>
            array(
                'required'                  => false,
                'name'                      => 'cover_composition',
                'vname'                     => 'LBL_COVER_COMPOSITION',
                'type'                      => 'text',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'size'                      => '20',
                'studio'                    => 'visible',
                'rows'                      => '4',
                'cols'                      => '20',
            ),
        'number_daily_wash_cycles' =>
            array(
                'required'                  => false,
                'name'                      => 'number_daily_wash_cycles',
                'vname'                     => 'LBL_NUMBER_DAILY_WASH_CYCLES',
                'type'                      => 'int',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
                'enable_range_search'       => false,
                'disable_num_format'        => '1',
                'min'                       => 0,
                'max'                       => 999,
                'validation'                =>
                    array(
                        'type' => 'range',
                        'min'  => 0,
                        'max'  => 999,
                    ),
            ),
        'competitor'               =>
            array(
                'required'                  => false,
                'name'                      => 'competitor',
                'vname'                     => 'LBL_COMPETITOR',
                'type'                      => 'varchar',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
            ),
        'detergent_used'           =>
            array(
                'required'                  => false,
                'name'                      => 'detergent_used',
                'vname'                     => 'LBL_DETERGENT_USED',
                'type'                      => 'varchar',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
            ),
        'brill_used'               =>
            array(
                'required'                  => false,
                'name'                      => 'brill_used',
                'vname'                     => 'LBL_BRILL_USED',
                'type'                      => 'varchar',
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => '',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'len'                       => '255',
                'size'                      => '20',
            ),
        'description'              =>
            array(
                'name'                      => 'description',
                'vname'                     => 'LBL_DESCRIPTION',
                'type'                      => 'text',
                'comment'                   => 'Full text of the note',
                'rows'                      => '6',
                'cols'                      => '80',
                'required'                  => false,
                'massupdate'                => 0,
                'no_default'                => false,
                'comments'                  => 'Full text of the note',
                'help'                      => '',
                'importable'                => 'true',
                'duplicate_merge'           => 'disabled',
                'duplicate_merge_dom_value' => '0',
                'audited'                   => false,
                'inline_edit'               => true,
                'reportable'                => true,
                'unified_search'            => false,
                'merge_filter'              => 'disabled',
                'size'                      => '20',
                'studio'                    => 'visible',
            ),
    ),
    'relationships'      => array(),
    'optimistic_locking' => true,
    'unified_search'     => true,
);
if (!class_exists('VardefManager'))
{
    require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('mkt_Inspection_Washing', 'mkt_Inspection_Washing',
                            array('basic', 'assignable', 'security_groups'));