<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'mkt',
  'author' => 'Adam Jakab',
  'description' => 'Modulo Lavorazioni',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Worklogs',
  'published_date' => '2016-08-09 09:56:37',
  'type' => 'module',
  'version' => 1470736597,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Worklogs',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'mkt_Worklogs',
      'class' => 'mkt_Worklogs',
      'path' => 'modules/mkt_Worklogs/mkt_Worklogs.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkt_worklogs_users_Users.php',
      'to_module' => 'Users',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkt_worklogs_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkt_worklogs_cases_Cases.php',
      'to_module' => 'Cases',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkt_worklogs_project_Project.php',
      'to_module' => 'Project',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkt_worklogs_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkt_worklogs_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkt_worklogs_usersMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkt_worklogs_tasksMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkt_worklogs_casesMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkt_worklogs_projectMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkt_worklogs_opportunitiesMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkt_worklogs_meetingsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/mkt_Worklogs',
      'to' => 'modules/mkt_Worklogs',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'it_IT',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'it_IT',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'it_IT',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Tasks.php',
      'to_module' => 'Tasks',
      'language' => 'it_IT',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'it_IT',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Cases.php',
      'to_module' => 'Cases',
      'language' => 'it_IT',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'it_IT',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Project.php',
      'to_module' => 'Project',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Project.php',
      'to_module' => 'Project',
      'language' => 'it_IT',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'it_IT',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'it_IT',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
      'language' => 'it_IT',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'en_us',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Meetings.php',
      'to_module' => 'Meetings',
      'language' => 'it_IT',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/it_IT.lang.php',
      'to_module' => 'application',
      'language' => 'it_IT',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_users_mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_users_Users.php',
      'to_module' => 'Users',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_tasks_mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_tasks_Tasks.php',
      'to_module' => 'Tasks',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_cases_mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_cases_Cases.php',
      'to_module' => 'Cases',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_project_mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_project_Project.php',
      'to_module' => 'Project',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_opportunities_mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_meetings_mkt_Worklogs.php',
      'to_module' => 'mkt_Worklogs',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkt_worklogs_meetings_Meetings.php',
      'to_module' => 'Meetings',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);